#!/bin/bash

TYPE=$(hostname | cut -c1-3)"Gce"

if [ "$TYPE" == "proGce" ]; then
    TYPE="prodGce"
fi

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Building Grunt $APP $TYPE..."
COMMAND=$(cat <<EOF
cd "/app" &&
new_path="\$(find / -name npm | head -1 | xargs -I % sh -c "dirname %")" &&
PATH="\$PATH:\$new_path" &&
PATH="\$PATH:\$(npm bin)" &&
npm install &&
bower --allow-root install &&
grunt build:$TYPE --force
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Built Grunt"
